In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import os
print(os.listdir("../input"))

['mnist.pkl.gz']


In [6]:
import gzip
import pickle

In [11]:
with open('../input/mnist.pkl.gz','rb') as f:
    a = pickle.load(f, encoding='bytes') # bytes unicode-escape

UnpicklingError: invalid load key, '\x1f'.

In [13]:
with gzip.open('../input/mnist.pkl.gz') as f:
    a = pickle.load(f, encoding='unicode-escape')

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:2: DeprecationWarning: invalid escape sequence '\>'
  
/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:2: DeprecationWarning: invalid escape sequence '\?'
  


In [18]:
with gzip.open('../input/mnist.pkl.gz') as f:
    a = pickle.load(f, encoding='bytes')

In [19]:
a

((array([[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]], dtype=float32),
  array([5, 0, 4, ..., 8, 4, 8])),
 (array([[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]], dtype=float32),
  array([3, 8, 6, ..., 5, 6, 8])),
 (array([[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]], dtype=float32),
  array([7, 2, 1, ..., 4, 5, 6])))